### ISSUE TITLE
 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.

### ISSUE THREAD

**Issue by c4milo** [philips/grpc-gateway-example#11]
I just cloned and compiled this project, then ran: **./grpc-gateway-example serve**; and got flooded with these messages: 

```sh
2016/08/11 16:35:16 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:10000: getsockopt: connection refused"; Reconnecting to {"localhost:10000" <nil>}
2016/08/11 16:35:16 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/11 16:35:16 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/11 16:35:16 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/11 16:35:16 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
```
**Go version:** 1.7rc6

**Comment by c4milo** [comment]
I'm not completely sure but I have suspect this issue may have been introduced by https://github.com/grpc/grpc-go/pull/514

**Comment by c4milo** [comment]
I did some more digging and it seems grpc-go is not setting the content-type header.

**Comment by jjeffery** [comment]
I just followed instructions at https://coreos.com/blog/gRPC-protobufs-swagger.html and experienced the same problem.

```
$ grpc-gateway-example serve
2016/08/24 18:20:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:10000: getsockopt: connection refused"; Reconnecting to {"localhost:10000" <nil>}
grpc on port: 10000
2016/08/24 18:20:48 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/24 18:20:48 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/24 18:20:48 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/24 18:20:48 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/08/24 18:20:48 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
```

Works fine on go1.6.2, fails on go1.7.

**Comment by ehernandez-xk** [comment]
I have the same problem after update to the newest go1.7 version.

**Comment by c4milo** [comment]
I was able to make it work only by using  `srv.ListenAndServeTLS()` explicitly.

**Comment by philips** [comment]
@c4milo do you have a patch?

**Comment by philips** [comment]
Fixed via https://github.com/philips/grpc-gateway-example/commit/e1dfd2244c42e44a2220bfc28393f3a7d25ddc0d

**Comment by ehernandez-xk** [comment]
This is the reason: https://golang.org/doc/go1.7#net_http

**Comment by kalbasit** [comment]
and the actual commit https://github.com/golang/go/commit/b5f0aff49503e31002b33198e06708e263c445a7

**Comment by atombender** [comment]
How does one fix this for non-TLS servers? Providing a dummy `TLSConfig` doesn't help.

**Comment by philips** [comment]
@atombender I don't really want to do non-TLS. I would rather that people use TLS but in untrusted mode. There is really no reason not use TLS all the time in 2016.

**Comment by atombender** [comment]
@philips For production, I agree. But for development — testing, debugging, tracing — forced TLS is really inconvenient.

**Comment by c4milo** [comment]
for dev is fine, I use a self-signed certificate with go build tags. The development workflow is not as bad I was imagining.

**Comment by hoffin** [comment]
Anyone have a solution without TLS? I'm using a proxy (Linkerd) that provided the TLS and using an API gateway for endpoint. I know this may be beyond the scope of this solution but running without TLS is an option for some :)

**Comment by AlekSi** [comment]
If someone is trying to make it work without TLS – you can't do it yet due to https://github.com/grpc/grpc-go/issues/555. Hope it will save you some time.

**Comment by Raffo** [comment]
@AlekSi I tried this months ago and came back to see if something changed. It's pretty bad that this is totally undocumented and I don't understand why we should be forced to terminate SSL in the app.

**Comment by mmailhos** [comment]
Just like you can't have both `tls.RequireAndVerifyClientCert` on the grpc handler *and*  `tls.NoClientCert` on the HTTP side. Too bad
