### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by bruth** [philips/grpc-gateway-example#4]
Hi! I was reading your [Take a REST with HTTP/2, Protobufs, and Swagger](https://coreos.com/blog/gRPC-protobufs-swagger.html) article and ran the following to try out the example myself:

```bash
$ go get -u github.com/philips/grpc-gateway-example
```

However it fails with the following errors.

```bash
$ go get -u github.com/philips/grpc-gateway-example
# github.com/philips/grpc-gateway-example/echopb
echopb/service.pb.gw.go:90: not enough arguments in call to runtime.HTTPError
echopb/service.pb.gw.go:94: not enough arguments in call to forward_EchoService_Echo_0
```

My guess is that the dependencies APIs have changed since you wrote the example?

**Comment by philips** [comment]
@bruth fixed, lmk if it works!

**Comment by bruth** [comment]
I can confirm it works, thanks!
