### ISSUE TITLE
architectural question: Can i generate the JS client proxy code ?

### ISSUE THREAD

**Issue by joeblew99** [philips/grpc-gateway-example#5]
I am using react web and react native.
One of the big things about React native is that you can update the app, without going through the long wait in the app stores.

SO, i am wondering if there is a way or approach where i can generate the JS client proxy code that talks to the GRPC Gateway.

Or am i taking the wrong approach maybe ?

**Comment by joeblew99** [comment]
I see that there is a https://localhost:10000/swagger.json

So i presume from this i can Code Gen the client proxy  then using a third party generator ?
If so, any go based ones ?

**Comment by philips** [comment]
Yes, you can do the JS stuff client side. There are tons of examples on the web.

**Comment by joeblew99** [comment]
cheers
